-- Highlights for the plugins in this config (and common AstroNvim companions).
return function(p)
  local bg_alt = p.bg_alt

  return {
    -- ── snacks.nvim (dashboard, picker, notifier, indent, input) ──────────────
    SnacksNormal = { fg = p.fg, bg = bg_alt },
    SnacksNormalNC = { fg = p.fg, bg = bg_alt },
    SnacksBackdrop = { bg = p.bg_dark },
    SnacksWinBar = { fg = p.fg_dim, bg = bg_alt },
    SnacksWinBarNC = { fg = p.comment, bg = bg_alt },

    SnacksDashboardHeader = { fg = p.cyan, bold = true },
    SnacksDashboardFooter = { fg = p.comment, italic = true },
    SnacksDashboardDesc = { fg = p.fg },
    SnacksDashboardIcon = { fg = p.cyan },
    SnacksDashboardKey = { fg = p.amber },
    SnacksDashboardTitle = { fg = p.cyan, bold = true },
    SnacksDashboardSpecial = { fg = p.cyan_dim },
    SnacksDashboardDir = { fg = p.comment },

    SnacksPicker = { fg = p.fg, bg = bg_alt },
    SnacksPickerBorder = { fg = p.border, bg = bg_alt },
    SnacksPickerTitle = { fg = p.cyan, bg = bg_alt, bold = true },
    SnacksPickerPrompt = { fg = p.cyan },
    SnacksPickerInputBorder = { fg = p.border, bg = bg_alt },
    SnacksPickerMatch = { fg = p.cyan, bold = true },
    SnacksPickerDir = { fg = p.comment },
    SnacksPickerSelected = { fg = p.amber },
    SnacksPickerListCursorLine = { bg = p.bg_high },

    SnacksNotifierInfo = { fg = p.cyan, bg = bg_alt },
    SnacksNotifierWarn = { fg = p.amber, bg = bg_alt },
    SnacksNotifierError = { fg = p.red, bg = bg_alt },
    SnacksNotifierDebug = { fg = p.fg_dim, bg = bg_alt },
    SnacksNotifierTrace = { fg = p.magenta, bg = bg_alt },
    SnacksNotifierIconInfo = { fg = p.cyan },
    SnacksNotifierIconWarn = { fg = p.amber },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierTitleInfo = { fg = p.cyan, bold = true },
    SnacksNotifierTitleWarn = { fg = p.amber, bold = true },
    SnacksNotifierTitleError = { fg = p.red, bold = true },
    SnacksNotifierBorderInfo = { fg = p.cyan_dim, bg = bg_alt },
    SnacksNotifierBorderWarn = { fg = p.amber_dim, bg = bg_alt },
    SnacksNotifierBorderError = { fg = p.red, bg = bg_alt },

    SnacksIndent = { fg = p.border },
    SnacksIndentScope = { fg = p.cyan_dim },
    SnacksInputBorder = { fg = p.cyan_dim, bg = bg_alt },
    SnacksInputTitle = { fg = p.cyan, bold = true },

    -- ── noice.nvim ────────────────────────────────────────────────────────────
    NoiceCmdline = { fg = p.fg, bg = bg_alt },
    NoiceCmdlineIcon = { fg = p.cyan },
    NoiceCmdlinePopup = { fg = p.fg, bg = bg_alt },
    NoiceCmdlinePopupBorder = { fg = p.cyan_dim, bg = bg_alt },
    NoiceCmdlinePopupTitle = { fg = p.cyan, bold = true },
    NoiceCmdlineIconSearch = { fg = p.amber },
    NoiceCmdlinePopupBorderSearch = { fg = p.amber_dim },
    NoicePopupmenu = { fg = p.fg, bg = bg_alt },
    NoicePopupmenuBorder = { fg = p.border, bg = bg_alt },
    NoicePopupmenuSelected = { fg = p.fg_bright, bg = p.bg_sel, bold = true },
    NoicePopupmenuMatch = { fg = p.cyan, bold = true },
    NoiceMini = { fg = p.fg_dim, bg = bg_alt },
    NoiceConfirm = { fg = p.fg, bg = bg_alt },
    NoiceConfirmBorder = { fg = p.cyan_dim, bg = bg_alt },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceLspProgressClient = { fg = p.cyan },
    NoiceLspProgressSpinner = { fg = p.cyan },
    NoiceVirtualText = { fg = p.cyan_dim },

    -- ── blink.cmp (AstroNvim v6 default completion) ───────────────────────────
    BlinkCmpMenu = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpMenuSelection = { fg = p.fg_bright, bg = p.bg_sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = p.border },
    BlinkCmpScrollBarGutter = { bg = p.bg_alt },
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelDeprecated = { fg = p.comment, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.cyan, bold = true },
    BlinkCmpLabelDetail = { fg = p.comment },
    BlinkCmpLabelDescription = { fg = p.comment },
    BlinkCmpKind = { fg = p.cyan },
    BlinkCmpSource = { fg = p.comment },
    BlinkCmpGhostText = { fg = p.comment, italic = true },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpDocSeparator = { fg = p.border },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.cyan, bold = true },

    -- ── nvim-cmp (in case it is used) ─────────────────────────────────────────
    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.cyan, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.cyan, bold = true },
    CmpItemMenu = { fg = p.comment, italic = true },
    CmpItemKind = { fg = p.cyan },
    CmpGhostText = { fg = p.comment, italic = true },

    -- ── gitsigns.nvim ─────────────────────────────────────────────────────────
    GitSignsAdd = { fg = p.git_add },
    GitSignsChange = { fg = p.git_change },
    GitSignsDelete = { fg = p.git_delete },
    GitSignsAddNr = { fg = p.git_add },
    GitSignsChangeNr = { fg = p.git_change },
    GitSignsDeleteNr = { fg = p.git_delete },
    GitSignsAddLn = { bg = p.diff_add },
    GitSignsChangeLn = { bg = p.diff_change },
    GitSignsDeleteLn = { bg = p.diff_delete },
    GitSignsCurrentLineBlame = { fg = p.comment, italic = true },
    GitSignsAddInline = { bg = p.diff_text },
    GitSignsDeleteInline = { bg = p.diff_delete },

    -- ── neo-tree.nvim ─────────────────────────────────────────────────────────
    -- Panel uses the lighter `bg_alt` shade so it reads as a soft raised sidebar
    -- (distinct from the editor) instead of a heavy pitch-black block.
    NeoTreeNormal = { fg = p.fg, bg = p.bg_alt },
    NeoTreeNormalNC = { fg = p.fg, bg = p.bg_alt },
    NeoTreeEndOfBuffer = { fg = p.bg_alt, bg = p.bg_alt },
    NeoTreeWinSeparator = { fg = p.border, bg = p.bg_alt },
    NeoTreeRootName = { fg = p.cyan, bold = true },
    NeoTreeDirectoryName = { fg = p.fg },
    NeoTreeDirectoryIcon = { fg = p.cyan_dim },
    NeoTreeFileName = { fg = p.fg },
    NeoTreeFileIcon = { fg = p.fg_dim },
    NeoTreeIndentMarker = { fg = p.border },
    NeoTreeExpander = { fg = p.comment },
    NeoTreeDotfile = { fg = p.comment },
    NeoTreeHiddenByName = { fg = p.comment },
    NeoTreeSymbolicLinkTarget = { fg = p.cyan },
    NeoTreeTitleBar = { fg = p.bg, bg = p.cyan },
    NeoTreeFloatBorder = { fg = p.border, bg = p.bg_alt },
    NeoTreeFloatTitle = { fg = p.cyan, bg = p.bg_alt, bold = true },
    NeoTreeGitAdded = { fg = p.git_add },
    NeoTreeGitModified = { fg = p.git_change },
    NeoTreeGitDeleted = { fg = p.git_delete },
    NeoTreeGitUntracked = { fg = p.cyan_dim, italic = true },
    NeoTreeGitIgnored = { fg = p.comment },
    NeoTreeGitConflict = { fg = p.red, bold = true },
    NeoTreeGitStaged = { fg = p.green },
    NeoTreeTabActive = { fg = p.fg_bright, bg = p.bg_alt, bold = true },
    NeoTreeTabInactive = { fg = p.comment, bg = p.bg_dark },
    NeoTreeTabSeparatorActive = { fg = p.cyan_dim, bg = p.bg_alt },
    NeoTreeTabSeparatorInactive = { fg = p.bg_dark, bg = p.bg_dark },

    -- ── leap.nvim / flit.nvim (jump labels) ───────────────────────────────────
    LeapMatch = { fg = p.cyan_bright, bold = true, underline = true },
    LeapLabel = { fg = p.bg, bg = p.amber, bold = true },
    LeapLabelPrimary = { fg = p.bg, bg = p.amber, bold = true },
    LeapLabelSecondary = { fg = p.bg, bg = p.cyan, bold = true },
    LeapBackdrop = { fg = p.comment },
    FlashMatch = { fg = p.cyan_bright, bold = true },
    FlashLabel = { fg = p.bg, bg = p.amber, bold = true },
    FlashBackdrop = { fg = p.comment },

    -- ── neotest ───────────────────────────────────────────────────────────────
    NeotestPassed = { fg = p.green },
    NeotestFailed = { fg = p.red },
    NeotestRunning = { fg = p.amber },
    NeotestSkipped = { fg = p.fg_dim },
    NeotestTest = { fg = p.fg },
    NeotestNamespace = { fg = p.cyan },
    NeotestFile = { fg = p.cyan_dim },
    NeotestDir = { fg = p.fg_dim },
    NeotestFocused = { fg = p.cyan, bold = true },
    NeotestAdapterName = { fg = p.magenta },
    NeotestExpandMarker = { fg = p.border },
    NeotestIndent = { fg = p.border },
    NeotestMarked = { fg = p.amber, bold = true },
    NeotestWinSelect = { fg = p.cyan },
    NeotestUnknown = { fg = p.fg_dim },
    NeotestWatching = { fg = p.amber },

    -- ── mason.nvim ────────────────────────────────────────────────────────────
    MasonHeader = { fg = p.bg, bg = p.cyan, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.amber, bold = true },
    MasonHighlight = { fg = p.cyan },
    MasonHighlightBlock = { fg = p.bg, bg = p.cyan },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.cyan, bold = true },
    MasonHighlightSecondary = { fg = p.amber },
    MasonHighlightBlockSecondary = { fg = p.bg, bg = p.amber },
    MasonMuted = { fg = p.comment },
    MasonMutedBlock = { fg = p.fg_dim, bg = p.bg_high },
    MasonError = { fg = p.red },

    -- ── which-key.nvim ────────────────────────────────────────────────────────
    WhichKey = { fg = p.cyan },
    WhichKeyGroup = { fg = p.amber },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.comment },
    WhichKeyValue = { fg = p.comment },
    WhichKeyFloat = { bg = p.bg_alt },
    WhichKeyBorder = { fg = p.border, bg = p.bg_alt },
    WhichKeyTitle = { fg = p.cyan, bg = p.bg_alt, bold = true },

    -- ── telescope.nvim (if present) ───────────────────────────────────────────
    TelescopeNormal = { fg = p.fg, bg = p.bg_alt },
    TelescopeBorder = { fg = p.border, bg = p.bg_alt },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_high },
    TelescopePromptBorder = { fg = p.bg_high, bg = p.bg_high },
    TelescopePromptTitle = { fg = p.bg, bg = p.cyan, bold = true },
    TelescopePromptPrefix = { fg = p.cyan },
    TelescopePromptCounter = { fg = p.comment },
    TelescopeResultsTitle = { fg = p.bg_alt, bg = p.bg_alt },
    TelescopePreviewTitle = { fg = p.bg, bg = p.amber, bold = true },
    TelescopeSelection = { fg = p.fg_bright, bg = p.bg_high, bold = true },
    TelescopeSelectionCaret = { fg = p.cyan, bg = p.bg_high },
    TelescopeMatching = { fg = p.cyan, bold = true },

    -- ── treesitter-context ────────────────────────────────────────────────────
    TreesitterContext = { bg = p.bg_alt },
    TreesitterContextLineNumber = { fg = p.gutter_active, bg = p.bg_alt },
    TreesitterContextSeparator = { fg = p.border },

    -- ── indent-blankline (if used) ────────────────────────────────────────────
    IblIndent = { fg = p.border },
    IblWhitespace = { fg = p.border },
    IblScope = { fg = p.cyan_dim },

    -- ── nvim-notify (fallback notifier) ───────────────────────────────────────
    NotifyINFOIcon = { fg = p.cyan },
    NotifyWARNIcon = { fg = p.amber },
    NotifyERRORIcon = { fg = p.red },
    NotifyDEBUGIcon = { fg = p.fg_dim },
    NotifyTRACEIcon = { fg = p.magenta },
    NotifyINFOTitle = { fg = p.cyan, bold = true },
    NotifyWARNTitle = { fg = p.amber, bold = true },
    NotifyERRORTitle = { fg = p.red, bold = true },
    NotifyINFOBorder = { fg = p.cyan_dim },
    NotifyWARNBorder = { fg = p.amber_dim },
    NotifyERRORBorder = { fg = p.red },
    NotifyDEBUGBorder = { fg = p.border },
    NotifyTRACEBorder = { fg = p.magenta },

    -- ── copilot ───────────────────────────────────────────────────────────────
    CopilotSuggestion = { fg = p.comment, italic = true },
    CopilotAnnotation = { fg = p.cyan_dim, italic = true },

    -- ── nvim-dap / dap-ui ─────────────────────────────────────────────────────
    DapBreakpoint = { fg = p.red },
    DapBreakpointCondition = { fg = p.amber },
    DapLogPoint = { fg = p.cyan },
    DapStopped = { fg = p.green },
    DapStoppedLine = { bg = p.bg_high },
    DapUIVariable = { fg = p.fg },
    DapUIScope = { fg = p.cyan },
    DapUIType = { fg = p.type },
    DapUIValue = { fg = p.fg },
    DapUIModifiedValue = { fg = p.amber, bold = true },
    DapUIDecoration = { fg = p.cyan_dim },
    DapUIThread = { fg = p.green },
    DapUIStoppedThread = { fg = p.cyan },
    DapUISource = { fg = p.magenta },
    DapUILineNumber = { fg = p.gutter_active },
    DapUIFloatBorder = { fg = p.border, bg = p.bg_alt },
    DapUIWatchesEmpty = { fg = p.comment },
    DapUIWatchesValue = { fg = p.green },
    DapUIWatchesError = { fg = p.red },
    DapUIBreakpointsPath = { fg = p.cyan },
    DapUIBreakpointsInfo = { fg = p.green },
    DapUIBreakpointsCurrentLine = { fg = p.amber, bold = true },

    -- ── nvim-ts-rainbow / rainbow-delimiters (subtle, mono-leaning) ───────────
    RainbowDelimiterCyan = { fg = p.cyan },
    RainbowDelimiterBlue = { fg = p.blue },
    RainbowDelimiterViolet = { fg = p.magenta },
    RainbowDelimiterYellow = { fg = p.amber },
    RainbowDelimiterGreen = { fg = p.green },
    RainbowDelimiterOrange = { fg = p.amber_dim },
    RainbowDelimiterRed = { fg = p.red },

    -- ── vim-illuminate ────────────────────────────────────────────────────────
    IlluminatedWordText = { bg = p.bg_high },
    IlluminatedWordRead = { bg = p.bg_high },
    IlluminatedWordWrite = { bg = p.bg_high, underline = true },

    -- ── lazy.nvim ─────────────────────────────────────────────────────────────
    LazyNormal = { fg = p.fg, bg = p.bg_alt },
    LazyButton = { fg = p.fg, bg = p.bg_high },
    LazyButtonActive = { fg = p.bg, bg = p.cyan, bold = true },
    LazyH1 = { fg = p.bg, bg = p.cyan, bold = true },
    LazyProgressDone = { fg = p.cyan },
    LazyProgressTodo = { fg = p.border },
    LazySpecial = { fg = p.cyan },
    LazyComment = { fg = p.comment },

    -- ── nvim-surround / mini.surround highlight ───────────────────────────────
    NvimSurroundHighlight = { fg = p.bg, bg = p.amber },

    -- ── package-info.nvim ─────────────────────────────────────────────────────
    PackageInfoUpToDateVersion = { fg = p.green },
    PackageInfoOutdatedVersion = { fg = p.amber },
    PackageInfoInvalidVersion = { fg = p.red },
  }
end
